### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException on Decode

### ISSUE THREAD

**Issue by gustavoramos00** [newhoggy/hashids-scala#10]
When trying to decode the incorrect hash "4", the following error occurred.

```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[ArrayIndexOutOfBoundsException: 0]]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.6.jar:2.4.6]
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.6.jar:2.4.6]
        at play.core.server.Server$class.logExceptionAndGetResult$1(Server.scala:50) [play-server_2.11-2.4.6.jar:2.4.6]
        at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:59) [play-server_2.11-2.4.6.jar:2.4.6]
        at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:57) [play-server_2.11-2.4.6.jar:2.4.6]
        at scala.util.Either$RightProjection.flatMap(Either.scala:522) [scala-library-2.11.7.jar:na]
        at play.core.server.Server$class.getHandlerFor(Server.scala:57) [play-server_2.11-2.4.6.jar:2.4.6]
        at play.core.server.NettyServer.getHandlerFor(NettyServer.scala:33) [play-netty-server_2.11-2.4.6.jar:2.4.6]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$8.apply(PlayDefaultUpstreamHandler.scala:132) [play-netty-server_2.11-2.4.6.jar:2.4.6]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$8.apply(PlayDefaultUpstreamHandler.scala:132) [play-netty-server_2.11-2.4.6.jar:2.4.6]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
        at org.hashids.impl.package$.decode(package.scala:117) ~[hashids-scala_2.11-1.1.1-7d841a8.jar:1.1.1-7d841a8]
        at org.hashids.Hashids.decode(Hashids.scala:40) ~[hashids-scala_2.11-1.1.1-7d841a8.jar:1.1.1-7d841a8]
        at models.domain.ID$.unhash(ID.scala:21) ~[na:na]
        at models.domain.ID$.apply(ID.scala:19) ~[na:na]
        at models.domain.ID$$anon$3.bind(ID.scala:44) ~[na:na]
        at play.core.routing.RouteParams$$anonfun$fromPath$1$$anonfun$apply$2.apply(GeneratedRouter.scala:64) ~[play_2.11-2.4.6.jar:2.4.6]
        at play.core.routing.RouteParams$$anonfun$fromPath$1$$anonfun$apply$2.apply(GeneratedRouter.scala:64) ~[play_2.11-2.4.6.jar:2.4.6]
        at scala.util.Either.fold(Either.scala:99) [scala-library-2.11.7.jar:na]
        at play.core.routing.RouteParams$$anonfun$fromPath$1.apply(GeneratedRouter.scala:64) ~[play_2.11-2.4.6.jar:2.4.6]
        at play.core.routing.RouteParams$$anonfun$fromPath$1.apply(GeneratedRouter.scala:64) ~[play_2.11-2.4.6.jar:2.4.6]
```

Using version "1.1.1-7d841a8" with salt.

**Comment by newhoggy** [comment]
The error has been reproduced:

```
[error] ! Invalid hash should not cause out of bounds exception
[error]  Exception raised on property evaluation.
[error]  > ARG_0: "onalzmqofCxjmxypbnqkklCfuFgI"
[error]  > Exception: java.lang.StringIndexOutOfBoundsException: String index out of range: -19 (package.scala:42)
[error] org.hashids.impl.package$.hash(package.scala:42)
[error] org.hashids.impl.package$$anonfun$2.apply(package.scala:64)
[error] org.hashids.impl.package$$anonfun$2.apply(package.scala:60)
[error] org.hashids.impl.package$.encode(package.scala:60)
[error] org.hashids.Hashids.encode(Hashids.scala:17)
[error] org.hashids.Hashids.decode(Hashids.scala:41)
[error] org.hashids.Hashids.decodeHex(Hashids.scala:44)
[error] org.hashids.SpecHashids$$anonfun$15$$anonfun$apply$75.apply(SpecHashids.scala:152)
[error] org.hashids.SpecHashids$$anonfun$15$$anonfun$apply$75.apply(SpecHashids.scala:150)
[error] org.scalacheck.Prop$$anonfun$forAllShrink$1$$anonfun$3.apply(Prop.scala:714)
[error] org.scalacheck.Prop$$anonfun$forAllShrink$1$$anonfun$3.apply(Prop.scala:714)
[error] org.scalacheck.Prop$.secure(Prop.scala:458)
[error] org.scalacheck.Prop$$anonfun$forAllShrink$1.org$scalacheck$Prop$$anonfun$$result$1(Prop.scala:714)
[error] org.scalacheck.Prop$$anonfun$forAllShrink$1.apply(Prop.scala:751)
[error] org.scalacheck.Prop$$anonfun$forAllShrink$1.apply(Prop.scala:708)
[error] org.scalacheck.Prop$$anonfun$apply$5.apply(Prop.scala:293)
[error] org.scalacheck.Prop$$anonfun$apply$5.apply(Prop.scala:292)
[error] org.scalacheck.PropFromFun.apply(Prop.scala:21)
[error] org.scalacheck.Test$.org$scalacheck$Test$$workerFun$1(Test.scala:321)
[error] org.scalacheck.Test$$anonfun$2.apply(Test.scala:350)
[error] org.scalacheck.Test$$anonfun$2.apply(Test.scala:350)
[error] org.scalacheck.Platform$.runWorkers(Platform.scala:40)
[error] org.scalacheck.Test$.check(Test.scala:350)
[error] org.hashids.SpecHashids.check(SpecHashids.scala:8)
```

**Comment by newhoggy** [comment]
The Java implementation at https://github.com/jiecao-fm/hashids-java also fails the same way.  I'm inclined to think this is normal and that application code should catch exceptions and consider it a failed decode due to invalid hash or salt.

```
[error] ! Invalid hash should not cause out of bounds exception in Java implementation
[error]  Exception raised on property evaluation.
[error]  > ARG_0: "nIsvGufzEfoCjbrSZbdwfujeeeByxaihtEbttgkcsk"
[error]  > Exception: java.lang.ArrayIndexOutOfBoundsException: 0 (Hashids.java:302)
[error] org.hashids.Hashids._decode(Hashids.java:302)
[error] org.hashids.Hashids.decode(Hashids.java:188)
[error] org.hashids.Hashids.decodeHex(Hashids.java:222)
[error] org.hashids.scala.SpecHashids$$anonfun$15$$anonfun$apply$75.apply(SpecHashids.scala:160)
[error] org.hashids.scala.SpecHashids$$anonfun$15$$anonfun$apply$75.apply(SpecHashids.scala:158)
[error] org.scalacheck.Prop$$anonfun$forAllShrink$1$$anonfun$3.apply(Prop.scala:714)
[error] org.scalacheck.Prop$$anonfun$forAllShrink$1$$anonfun$3.apply(Prop.scala:714)
[error] org.scalacheck.Prop$.secure(Prop.scala:458)
[error] org.scalacheck.Prop$$anonfun$forAllShrink$1.org$scalacheck$Prop$$anonfun$$result$1(Prop.scala:714)
[error] org.scalacheck.Prop$$anonfun$forAllShrink$1.apply(Prop.scala:751)
[error] org.scalacheck.Prop$$anonfun$forAllShrink$1.apply(Prop.scala:708)
[error] org.scalacheck.Prop$$anonfun$apply$5.apply(Prop.scala:293)
[error] org.scalacheck.Prop$$anonfun$apply$5.apply(Prop.scala:292)
[error] org.scalacheck.PropFromFun.apply(Prop.scala:21)
[error] org.scalacheck.Test$.org$scalacheck$Test$$workerFun$1(Test.scala:321)
[error] org.scalacheck.Test$$anonfun$2.apply(Test.scala:350)
[error] org.scalacheck.Test$$anonfun$2.apply(Test.scala:350)
[error] org.scalacheck.Platform$.runWorkers(Platform.scala:40)
[error] org.scalacheck.Test$.check(Test.scala:350)
[error] org.hashids.scala.SpecHashids.check(SpecHashids.scala:8)
```

**Comment by newhoggy** [comment]
I have checked the Javascript implementation.  It returns an empty array in such cases, so I will add the necessary checks to do the same.

**Comment by newhoggy** [comment]
New version `1.1.2-2974446` has been published with the fix.
